"""add topic and preferred_language

Revision ID: 57d244c75a31
Revises: 4e4d8fa6d59b
Create Date: 2026-06-09 12:12:22.219893
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '57d244c75a31'
down_revision: Union[str, None] = '4e4d8fa6d59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('topic', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_questions_level'), 'questions', ['level'], unique=False)
    op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)
    op.add_column('users', sa.Column('preferred_language', sa.String(length=8), server_default='uz', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_index(op.f('ix_questions_level'), table_name='questions')
    op.drop_column('questions', 'topic')
    # ### end Alembic commands ###
