"""add relevance_score to evaluations

Revision ID: bdb587957991
Revises: dc74c9831f93
Create Date: 2026-06-10 07:14:43.803108
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bdb587957991'
down_revision: Union[str, None] = 'dc74c9831f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('relevance_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'relevance_score')
    # ### end Alembic commands ###
