"""add topic_images

Revision ID: dc74c9831f93
Revises: 9a1299de938d
Create Date: 2026-06-09 14:10:44.198310
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc74c9831f93'
down_revision: Union[str, None] = '9a1299de938d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('image_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_images_topic_id'), 'topic_images', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_images_topic_id'), table_name='topic_images')
    op.drop_table('topic_images')
    # ### end Alembic commands ###
