"""add topics table

Revision ID: f8f624b844ca
Revises: 57d244c75a31
Create Date: 2026-06-09 12:27:38.238529
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8f624b844ca'
down_revision: Union[str, None] = '57d244c75a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'name', name='uq_topic_teacher_name')
    )
    op.create_index(op.f('ix_topics_teacher_id'), 'topics', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_teacher_id'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
